sudo: false
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
           - george-edison55-precise-backports
        packages:
           - cmake
           - cmake-data
           - gcc-6
           - g++-6
           - binutils
           - gfortran
           - libblas-dev
           - liblapack-dev
           - libgmp-dev
           - libmpfr-dev
 
matrix:
    include:
       - language: julia
         julia: 1.0
         os: linux
       - language: julia
         julia: 1.0
         os: osx
install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$HOME/usr/bin:$PATH"; fi
    - export THE_PKG_DIR=`julia -e 'println(Pkg.dir())'`

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ ! -f $HOME/usr/bin/ld ]; then
         wget https://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.gz;
         tar xzf binutils-2.27.tar.gz;
         (cd binutils-2.27 && ./configure --prefix=$HOME/usr && make && make install);
      fi;
    - if [ ! -f $HOME/early_abort ]; then julia -e 'using Pkg; Pkg.clone("https://github.com/oscar-system/Singular.jl")' || false; fi
    - while sleep 30; do echo "still alive"; done &
    - if [ ! -f $HOME/early_abort ]; then julia -e 'Pkg.build("Singular")' || false; fi
    - if [ ! -f $HOME/early_abort ]; then julia -e 'Pkg.test("Singular"; coverage=true)' || false; fi

notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Singular"); Pkg.test("Singular"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Singular")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Singular")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
