# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial

language: julia
julia:
   - 1.0
   - 1.1
   - 1.2
   - nightly

addons:
    apt:
        packages:
           - cmake
           - cmake-data
           - gfortran
           - libblas-dev
           - liblapack-dev
           - libgmp-dev
           - libmpfr-dev
 
matrix:
    include:
       - os: linux
       - os: osx

script:
    - while sleep 30; do echo "still alive"; done &
    - julia -e 'using Pkg; Pkg.build("Singular"); Pkg.test("Singular");'

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Pkg; cd(Pkg.dir("Singular")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'using Pkg; cd(Pkg.dir("Singular")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:                                                                             include:                                                                         - stage: "Documentation"                                                         julia: 1.0                                                                     os: linux                                                                      script:
         - while sleep 30; do echo "still alive"; done &
         - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate();'
         - julia --project=docs/ docs/make.jl
       after_success: skip
