name = "Singular"
uuid = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
version = "0.25.99"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
BinaryWrappers = "f01c122e-0ea1-4f85-ad8f-907073ad7a9f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomExtensions = "fb686558-2515-59ef-acaa-46db3789a887"
Singular_jll = "43d676ae-4934-50ba-8046-7a96366d613b"
lib4ti2_jll = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
libsingular_julia_jll = "ae4fbd8f-ecdb-54f8-bbce-35570499b30e"

[compat]
AbstractAlgebra = "0.43.1, 0.44, 0.45, 0.46"
BinaryWrappers = "~0.1.1"
CxxWrap = "~0.17"
FileWatching = "1.10"
Libdl = "1.6"
LinearAlgebra = "1.6"
Nemo = "0.47, 0.48, 0.49, 0.50, 0.51"
Pkg = "1.6"
Random = "1.6"
RandomExtensions = "0.4.2"
Singular_jll = "=404.101.301"
julia = "1.10"
lib4ti2_jll = "1.6.10"
libsingular_julia_jll = "=0.47.6"
