name = "Singular"
uuid = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
version = "0.2.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"

[compat]
AbstractAlgebra = "^0.8.0"
Nemo = "^0.16.0"
julia = "1.0.0 1.1 1.2 1.3 1.4"
CxxWrap = "^0.9"
BinaryProvider = "^0.5.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
